name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout Mongo
        uses: actions/checkout@v2
        with:
          path: vlib/mongo
      - name: Install V dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libglfw3-dev libxi-dev libxcursor-dev
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: Install Mongo dependencies
        run: |
          cd ./vlib/mongo/src
          sudo make install
      - name: MongoDB Community Server
        run: |
          curl -LO https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/7.0/multiverse/binary-amd64/mongodb-org-server_7.0.2_amd64.deb
          sudo apt install -y ./mongodb-org-server_7.0.2_amd64.deb
          mmkdir -p data
          mongod --dbpath data &
      - name: Test
        run: |
          cd ./vlib/mongo/
          v -stats test .
      - name: Build Mongo shared lib
        run: |
          cd ./vlib/mongo/
          v -shared .
      - name: Build Mongo example
        run: |
          cd ./vlib/mongo/examples/
          v -prod count-example.v
          v -prod find-example.v
          v -prod find-lean-example.v
          v -prod insert-example.v