name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout Mongo
        uses: actions/checkout@v2
        with:
          path: vlib/mongo
      - name: Install V dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libglfw3-dev libxi-dev libxcursor-dev
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: Install Mongo dependencies
        run: |
          cd ./vlib/mongo/
          sudo make install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Test
        run: |
          cd ./vlib/mongo/
          make test
      - name: Build Mongo example
        run: |
          cd ./vlib/mongo/examples/
          v -prod example.v

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout Mongo
        uses: actions/checkout@v2
        with:
          path: vlib/mongo
      - name: Install V dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libglfw3-dev libxi-dev libxcursor-dev
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: Install Mongo dependencies
        run: |
          cd ./vlib/mongo/
          sudo make
      - name: Build Mongo shared lib
        run: |
          cd ./vlib/mongo/
          make build